name: Action Test Ubuntu

on:
  push:
    paths:
      - '.github/workflows/action-test-linux.yaml'
      - 'action.yaml'
      - 'runtime.py'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: stack-spot/runtime-manager-action@main
        with:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_KEY: ${{ secrets.CLIENT_KEY }}
          CLIENT_REALM: ${{ secrets.CLIENT_REALM }}