name: Action Test Ubuntu

on:
  push:
    paths:
      - '.github/workflows/action-test-ubuntu.yaml'
      - 'action.yaml'
      - 'runtime.py'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: stack-spot/runtime-manager-action@main
        with:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_KEY: ${{ secrets.CLIENT_KEY }}
          CLIENT_REALM: ${{ secrets.CLIENT_REALM }}
          WORKSPACE: Runtimes
          ENVIRONMENT: production
          VERSION_TAG: ${{ github.sha }}
          TF_STATE_BUCKET_NAME: test
          TF_STATE_REGION: test
          IAC_BUCKET_NAME: test
          IAC_REGION: test
          CHECKOUT_BRANCH: main