name: Test

on:
  push:
  workflow_dispatch:

jobs:
  # orchestration:
  #   runs-on: ubuntu-latest
  #   outputs: 
  #     tasks: ${{ steps.tasks.outputs.tasks }}
  #   steps:
  #     - name: Build Tasks Array
  #       id: tasks
  #       run: |
  #         echo "tasks=$myArray" >> $GITHUB_OUTPUT
  #       shell: bash
  
  deploy:
    runs-on: ubuntu-latest
    # needs: [orchestration]
    strategy:
      matrix:
        task: [{'order': 0, 'runTaskId': '01HBGYVEY6J3120461MAK4RY2E', 'taskType': 'IAC_SELF_HOSTED', 'pluginAppliedAlias': 'plugin1'}, {'order': 1, 'runTaskId': '01HBGYVEY6NSQ4RHPWWFEBYWPC', 'taskType': 'IAC_SELF_HOSTED', 'pluginAppliedAlias': 'plugin1'}, {'order': 2, 'runTaskId': '01HBGYVEY65Z5DVHAZ4RHMGEV9', 'taskType': 'DEPLOY_SELF_HOSTED', 'pluginAppliedAlias': 'plugin2'}, {'order': 3, 'runTaskId': '01HBGYVEY6A3396A61F5SC0DPP', 'taskType': 'DEPLOY_SELF_HOSTED', 'pluginAppliedAlias': 'plugin2'}, {'order': 4, 'runTaskId': '01HBGYVEY62HAP5MGB2K13MNH6', 'taskType': 'DESTROY_SELF_HOSTED', 'pluginAppliedAlias': 'plugin3'}]
      fail-fast: true
      max-parallel: 1
    # set the environment to use (environment must exist and be named the same as the stage here)
    # environment:
    #   name: ${{ matrix.stage }}
    steps:
    # use environment specific secrets here for each stage
      - name: Worker IAC
        if: contains( matrix.task.taskType , 'IAC')
        run: echo ${{ matrix.task.runTaskId }}

      - name: Worker DEPLOY
        if: contains( matrix.task.taskType , 'DEPLOY')
        run: echo ${{ matrix.task.runTaskId }}

      - name: Worker DESTROY
        if: contains( matrix.task.taskType , 'DESTROY')
        run: echo ${{ matrix.task.runTaskId }}